import type { RequestHandler } from "express";

import type { AdminQuestionListQuery, AdminQuestionUpdateInput, AdminWeeklyLiveListQuery, CreateWeeklyLiveInput, PublicQuestionInput, UpdateWeeklyLiveInput, WeeklyLiveIdParams, WeeklyLiveQuestionIdParams } from "./weeklyLive.schema.js";
import { createWeeklyLive, deleteWeeklyLiveQuestion, getCurrentWeeklyLive, getWeeklyLive, getWeeklyLiveQuestion, listWeeklyLiveQuestions, listWeeklyLives, submitQuestion, updateWeeklyLive, updateWeeklyLiveQuestion } from "./weeklyLive.service.js";

export const getCurrentWeeklyLiveController: RequestHandler = async (_request, response, next) => { try { response.status(200).json({ success: true, live: await getCurrentWeeklyLive() }); } catch (error) { next(error); } };
export const submitQuestionController: RequestHandler = async (request, response, next) => { try { const { id } = response.locals.validatedParams as WeeklyLiveIdParams; const submission = await submitQuestion(id, request.body as PublicQuestionInput); response.status(201).json({ success: true, ...submission }); } catch (error) { next(error); } };
export const listWeeklyLivesController: RequestHandler = async (_request, response, next) => { try { response.status(200).json({ success: true, ...(await listWeeklyLives(response.locals.validatedQuery as AdminWeeklyLiveListQuery)) }); } catch (error) { next(error); } };
export const getWeeklyLiveController: RequestHandler = async (_request, response, next) => { try { const { id } = response.locals.validatedParams as WeeklyLiveIdParams; response.status(200).json({ success: true, live: await getWeeklyLive(id) }); } catch (error) { next(error); } };
export const createWeeklyLiveController: RequestHandler = async (request, response, next) => { try { response.status(201).json({ success: true, live: await createWeeklyLive(request.body as CreateWeeklyLiveInput) }); } catch (error) { next(error); } };
export const updateWeeklyLiveController: RequestHandler = async (request, response, next) => { try { const { id } = response.locals.validatedParams as WeeklyLiveIdParams; response.status(200).json({ success: true, live: await updateWeeklyLive(id, request.body as UpdateWeeklyLiveInput) }); } catch (error) { next(error); } };
export const listWeeklyLiveQuestionsController: RequestHandler = async (_request, response, next) => { try { const { id } = response.locals.validatedParams as WeeklyLiveIdParams; response.status(200).json({ success: true, ...(await listWeeklyLiveQuestions(id, response.locals.validatedQuery as AdminQuestionListQuery)) }); } catch (error) { next(error); } };
export const getWeeklyLiveQuestionController: RequestHandler = async (_request, response, next) => { try { const { questionId } = response.locals.validatedParams as WeeklyLiveQuestionIdParams; response.status(200).json({ success: true, question: await getWeeklyLiveQuestion(questionId) }); } catch (error) { next(error); } };
export const updateWeeklyLiveQuestionController: RequestHandler = async (request, response, next) => { try { const { questionId } = response.locals.validatedParams as WeeklyLiveQuestionIdParams; response.status(200).json({ success: true, question: await updateWeeklyLiveQuestion(questionId, request.body as AdminQuestionUpdateInput) }); } catch (error) { next(error); } };
export const deleteWeeklyLiveQuestionController: RequestHandler = async (_request, response, next) => { try { const { questionId } = response.locals.validatedParams as WeeklyLiveQuestionIdParams; await deleteWeeklyLiveQuestion(questionId); response.status(204).send(); } catch (error) { next(error); } };
